version: '3.8'

services:
  
  uni-db:
    image: mysql:8.0
    
    container_name: uni-mysql-db
    
    restart: on-failure
    
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      
      MYSQL_DATABASE: uni_db
      
    ports:
      - "3307:3306"
      
    volumes:
      - uni-db-data:/var/lib/mysql

volumes:
  uni-db-data: